export const LOAD_TODOLIST_START = 'LOAD_TODOLIST_START';
export const LOAD_TODOLIST_SUCCESS = 'LOAD_TODOLIST_SUCCESS';
export const LOAD_TODOLIST_FAIL = 'LOAD_TODOLIST_FAIL';

export const LOAD_PERSONS_START = 'LOAD_PERSONS_START';
export const LOAD_PERSONS_SUCCESS = 'LOAD_PERSONS_SUCCESS';
export const LOAD_PERSONS_FAIL = 'LOAD_PERSONS_FAIL';

export const LOAD_CATEGORIES_START = 'LOAD_CATEGORIES_START';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_FAIL = 'LOAD_CATEGORIES_FAIL';

export const POST_TODO_START = 'POST_TODO_START';
export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS';
export const POST_TODO_FAIL = 'POST_TODO_FAIL';

export const UPDATE_TODO_START = 'UPDATE_TODO_START';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAIL = 'UPDATE_TODO_FAIL';

export const DELETE_TODO_START = 'DELETE_TODO_START';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';

export const GET_TODO_START = 'GET_TODO_START';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_FAIL = 'GET_TODO_FAIL';

